// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface User {
  /**
   * Email
   */
  email: string;

  /**
   * First name
   */
  firstName?: string;

  /**
   * Last name
   */
  lastName?: string;

  /**
   * City
   */
  city?: string;

  /**
   * Phone
   */
  phone?: string;

  /**
   * Postal code
   */
  postalCode?: string;

  /**
   * Address
   */
  address?: string;

  /**
   * Country
   */
  country?: string;

  /**
   * Discord
   */
  discord?: string;

  /**
   * VK
   */
  vk?: string;

  /**
   * Facebook
   */
  facebook?: string;

  /**
   * Telegram
   */
  telegram?: string;

  /**
   * Kosticonnect 2021
   */
  kosticonnect2021?: number;

  /**
   * User image
   */
  userImage?: string;

  /**
   * Bookmarks
   */
  bookmarks?: Array<string>;

  /**
   * KMG Player
   */
  kmgPlayer: boolean;
}
